### ISSUE TITLE
功能非常棒👍，一点个人建议

### ISSUE THREAD

**Issue by fyhhub** [cxqdmm/automock#1]
mock响应值能不能直接放到侧边，是不是更方便点。感谢开源😁

<img width="375" alt="image" src="https://user-images.githubusercontent.com/38740836/177518897-5e7ffaa1-6441-4f49-80dd-ae5658ebecf4.png">

**Comment by cxqdmm** [comment]
感谢反馈，确实这样感觉更优雅

**Comment by cxqdmm** [comment]
已更新

**Comment by fyhhub** [comment]
感谢作者
